---
title: "The pros and cons of Open Sciece"
author: "Richèl Bilderbeek"
format: revealjs
editor: visual
from: markdown+emoji
bibliography: presentation.bib
csl: vancouver.csl
css: styles.css
slide-number: true
number-sections: true
number-offset: 0
---

# Who am I

- Open Science is a pleonasm
- Did not leave academia due to discovery of Open Science
- Abort a position in academia, as not allowed to do Open Science
- Started Open Science Uppsala

 * Q: who lives in a town with a local community?
 * Q: who visits that local community

# Open Science Uppsala

- The local Uppsala community
- in public library
- around 6 regular visitors
- many interruptions and discussions
- next talk: discussion on National Swedish Guidelines on Open Science
 

 * [some points in the discussion]
 * Lemma 1:
    * Proper science takes more time than sloppy science
    * Open Science forces proper science
    * Hence Open Sciences takes as much or more time
 * Lemma 2:
    * A goal of science is to uncover knowledge/facts/laws
    * Knowledge/facts/laws are reproducible
    * Science is as good as it is reproducible
 * Lemma 3:
    * Assume a sloppy scientist that starts doing Open Science,
      who takes twice as long per paper
    * Reproducibility of that paper goes up a factor of twenty [paper]
    * The scientist is 10x a better scientists


# References
