# Render Quarto presentations to PDF
name: Build PDFs

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 15 * *"


jobs:
  build_pdfs:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # These PDFs are there so that git does not check a PDF each change.
      # The idea is to put the PDFs created by GHA (i.e. this script)
      # there manually
      - name: Delete old PDFs
        run: rm $(find . | egrep "pdf$")

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: presentation.qmd

      #############################################
      # Upload
      #############################################
      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: zipped_presentation
          path: "**/*.pdf"
          if-no-files-found: error

