on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 15 * *"

name: check-links

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      # If there is a valid external link that fails,
      # add it to mlc_config.json
      - name: External links must be checked, do not allow '0' in the 'aliveStatusCodes' of mlc_config.json
        run: if [[ $(grep --regexp "[^0-9]0[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi

      - name: Internal links must checked, do not allow '400' in the 'aliveStatusCodes' of mlc_config.json
        run: if [[ $(grep --regexp "[^0-9]400[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
