# Check that there is correct spelling in all files
name: Lint markdown

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"


jobs:
  lint_markdown:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: DavidAnson/markdownlint-cli2-action@v13
        continue-on-error: true
